/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bed2.glb 
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useCustomization } from "@/contexts/Customization";

export function Bed(props) {
  const { nodes, materials } = useGLTF("/models/bed2.glb");
  const { bedValue, sheetValue, sheetFoldValue, pillowValue } =
    useCustomization();
  return (
    <group {...props} dispose={null} position={[0, -1, -2]}>
      <mesh geometry={nodes.lit.geometry}>
        <mesh
          geometry={nodes.matelaa.geometry}
          position={[-0.005, 0.248, 1.345]}
        >
          <group>
            <mesh
              geometry={nodes.drapPli.geometry}
              position={[0, 0.021, -1.004]}
            >
              <meshStandardMaterial color={sheetFoldValue} />
            </mesh>
            <mesh
              geometry={nodes.drapPli001.geometry}
              position={[0, 0.021, 1.267]}
            >
              <meshStandardMaterial color={sheetFoldValue} />
            </mesh>
          </group>
          <group>
            <mesh
              geometry={nodes.oreiller.geometry}
              position={[-0.573, 0.477, -2.247]}
            >
              <meshStandardMaterial color={pillowValue} />
            </mesh>
            <mesh
              geometry={nodes.oreiller001.geometry}
              position={[0.592, 0.489, -2.263]}
            >
              <meshStandardMaterial color={pillowValue} />
            </mesh>
            <mesh
              geometry={nodes.oreiller002.geometry}
              position={[0.578, 0.453, -1.99]}
            >
              <meshStandardMaterial color={pillowValue} />
            </mesh>
            <mesh
              geometry={nodes.oreiller003.geometry}
              material={materials.oreiller}
              position={[-0.575, 0.458, -1.942]}
            >
              <meshStandardMaterial color={pillowValue} />
            </mesh>
          </group>

          <meshStandardMaterial color={sheetValue} />
        </mesh>
        <meshStandardMaterial {...materials.lit} color={bedValue} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/bed2.glb");
